version: "3.9"
services:
  backend-db:
    container_name: backend-db
    image: postgres:bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge